import _Vue from "vue";
import { Options } from "./options";
declare const install: (Vue: typeof _Vue, options: Options) => void;
declare const noscript: (id: string, src?: string) => HTMLElement;
export { default as disable } from "./api/disable";
export { default as event } from "./api/event";
export { default as initialize } from "./api/initialize";
export { default as optIn } from "./api/opt-in";
export { default as optOut } from "./api/opt-out";
export { default as track } from "./api/track";
export { default as query } from "./api/query";
export { default as bootstrap } from "./bootstrap";
export { setOptions } from "./options";
export { install, noscript };
export default install;
